version: "3"
services:
  app:
    container_name: vuetify-sandbox
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8888:8888
    volumes:
      - .:/app
      - node_modules:/app/node_modules
volumes:
  node_modules: {}
