version: 2
jobs:
  build:
    docker:
      - image: node:12.14.0 # nodeのバージョンは開発環境に合わせる
    working_directory: ~/vuetify-sandbox
    steps:
     # グローバルインストール
      - run:
          name: Install global
          command: npm install -g @vue/cli
      # グローバルインストール
      - run:
          name: Install global
          command: npm install -g pm2
      # 依存関係のインストール
      - run:
          name: Install dependencies # CircleCI上で表示される処理名(任意)
          command: npm install # 処理コマンド
      #ls
      - run:
          name: Check dist
          command: ls
      # ビルド
      - run:
          name: Build
          command: npm run  build



      # ビルドの確認
      - run:
          name: run pm2
          command: pm2 serve --spa dist 5000
