version: 2
jobs:
  build:
    docker:
      - image: node:12.14.0 # nodeのバージョンは開発環境に合わせる

    working_directory: ~/vuetify-sandbox # 作業フォルダ

    steps:
      - checkout # プロジェクトに追加したGitHubリポジトリをworking_directoryにcloneしてcheckout

      # 依存関係のインストール
      - run:
          name: Install dependencies # CircleCI上で表示される処理名(任意)
          command: npm install # 処理コマンド

      # ビルド
      - run:
          name: Build
          command: npm run  build

      # ビルドの確認
      - run:
          name: Check dist
          command: ls -la dist
